	cmake_minimum_required(VERSION 2.6)
	add_executable(	break1 src/condition/break1.c	)
	add_executable(	for-loop-infinite src/condition/for-loop-infinite.c	)
	add_executable(	for-loop-nested src/condition/for-loop-nested.c	)
	add_executable(	unsigned src/keyword/unsigned.c	)
	add_executable(	void src/keyword/void.c	)
	add_executable(	auto src/storageClass/auto.c	)
	add_executable(	const src/storageClass/const.c	)
	add_executable(	extern src/storageClass/extern.c	)
	add_executable(	header header/header.h	)
	add_library( unsigned STATIC abc.a )
	add_library( unsigned SHARED XYZ.so )
