	cmake_minimum_required(VERSION 2.6)
	add_executable(	break1 src\condition\break1.c	)
	add_executable(	for-loop-diff-combination src\condition\for-loop-diff-combination.c	)
	add_executable(	for-loop-infinite src\condition\for-loop-infinite.c	)
	add_executable(	for-loop-nested src\condition\for-loop-nested.c	)
	add_executable(	for-loop1 src\condition\for-loop1.c	)
	add_executable(	for-loop2 src\condition\for-loop2.c	)
	add_executable(	goto src\condition\goto.c	)
	add_executable(	if src\condition\if.c	)
	add_executable(	if2 src\condition\if2.c	)
	add_executable(	if3 src\condition\if3.c	)
	add_executable(	nested_if src\condition\nested_if.c	)
	add_executable(	long src\keyword\long.c	)
	add_executable(	typedef src\keyword\typedef.c	)
	add_executable(	typedef2 src\keyword\typedef2.c	)
	add_executable(	unsigned src\keyword\unsigned.c	)
	add_executable(	void src\keyword\void.c	)
	add_executable(	void2 src\keyword\void2.c	)
	add_executable(	auto src\storageClass\auto.c	)
	add_executable(	const src\storageClass\const.c	)
	add_executable(	enum src\storageClass\enum.c	)
	add_executable(	extern src\storageClass\extern.c	)
	add_executable(	header header\header.h	)
	add_executable(	macro-1 src\storageClass\macro-1.c	)
	add_executable(	macro-2 src\storageClass\macro-2.c	)
	add_executable(	register src\storageClass\register.c	)


